version: 2

models:
    - name: employee
      description: "employee details model"
      columns:
          - name: employee_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null